{
  "type": "record",
  "name": "MarketPriceBronze",
  "namespace": "com.aetherstream.bronze.model",
  "fields": [
    { "name": "assetId", "type": "string" },
    { "name": "symbol", "type": "string" },
    { "name": "coinName", "type": "string" },
    { "name": "currency", "type": "string" },
    { "name": "price",
      "type": ["null", { "type": "bytes", "logicalType": "decimal", "precision": 38, "scale": 18 }],
      "default": null
    },
    { "name": "marketCap",
      "type": ["null", { "type": "bytes", "logicalType": "decimal", "precision": 38, "scale": 18 }],
      "default": null
    },
    { "name": "volume24h",
      "type": ["null", { "type": "bytes", "logicalType": "decimal", "precision": 38, "scale": 18 }],
      "default": null
    },
    { "name": "coinImage", "type": "string" },    
    { "name": "eventTimeMs", "type": "long" },
    { "name": "sourceTsMs", "type": "long" },
    { "name": "createdAtMs", "type": "long" },
    { "name": "updatedAtMs", "type": ["null", "long"], "default": null },
    { "name": "op", "type": "string" },
    { "name": "lsn", "type": ["null", "long"], "default": null },
    { "name": "sourceDb", "type": "string" },
    { "name": "sourceSchema", "type": "string" },
    { "name": "sourceTable", "type": "string" },
    { "name": "ingestion_date", "type": "string" },
    { "name": "ingestion_hour", "type": "string" }
  ]
}